# Introduction to Numpy
NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers. In some ways, NumPy arrays are like Python’s built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size. NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python, so time spent learning to use NumPy effectively will be valuable no matter what aspect of data science interests you.

In [16]:
# Load libraries
import numpy as np


## Creating Arrays from Python Lists
- First, we can use `np.array` to create arrays from Python lists.
- Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible.
- If we want to explicitly set the data type of the resulting array, we can use the dtype keyword.
- Finally, unlike Python lists, NumPy arrays can explicitly be multidimensional.

In [17]:
# Creating an integer array from a list
int_array = np.array( [1, 2, 3, 4, 5, 6])
print(int_array)

# Here, integers are upcast to floating point
float_array = np.array([1.0, 2, 3, 4, 5, 6])
print(float_array)

# We can use dtype keyword to specify the data type
type_array = np.array([1, 2, 3, 4], dtype = float)
print(type_array)

# Creating an multidimensional array
mult_array = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(mult_array)

[1 2 3 4 5 6]
[1. 2. 3. 4. 5. 6.]
[1. 2. 3. 4.]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


## Creating Arrays from Scratch
Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here I am goint to mention two methods that are more commonly used: `np.arange()` and `np.linspace()`

`np.arange()` stands for "NumPy array range" and is a function provided by the NumPy library in Python. It returns an array of evenly spaced values within a specified interval. The syntax for using np.arange() is: 
        
        np.arange([start,] stop[, step,], dtype = None)

Where: 
- `start`: (optional): The start of the interval. If not specified, the default value is 0.
- `stop`: The end of the interval. This parameter is required.
- `step` (optional): The step size between each pair of adjacent values in the array. If not specified, the default value is 1.
- `dtype` (optional): The data type of the array. If not specified, NumPy will choose the appropriate data type based on the other parameters.

`np.linspace()` is another function provided by the NumPy library in Python. It returns an array of evenly spaced numbers over a specified interval. The syntax for using linspace() is:

        np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype = None)

Where:
- `start`: The start of the interval. This parameter is required.
- `stop`: The end of the interval. This parameter is required.
- `num`: (optional): The number of values to generate. Default value is 50.
- `endpoint`: (optional): Whether to include the end value in the array. Default value is True.
- `retstep`: (optional): Whether to return the step value that was used. Default value is False.
- `dtype`: (optional): The data type of the array. If not specified, NumPy will choose the appropriate data type based on the other parameters.


In [29]:
# Create a length-10 integer array filled with zeros
zero_array = np.zeros(shape = 10, dtype = int)
print(zero_array)

# Create a 3x5 floating-point array filled with 1s
one_array = np.ones(shape = (3, 5), dtype = float)
print(one_array)

# Create a 3x5 array filled with 3.14
value_array = np.full(shape = (3, 5), fill_value = 3.14)
print(value_array)

# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
seq_array = np.arange(start = 0, stop = 20, step = 2)
print(seq_array)

# Create an array of five values evenly spaced between 0 and 1
even_array = np.linspace(start = 0, stop = 1, num = 5)
print(even_array)

# Create a 3x3 identity matrix
identity_array = np.eye(N = 3)
print(identity_array)

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Random Module
The `np.random` module is a sub-module of the NumPy library which provides functions for generating random numbers. It's commonly used in machine learning applications, simulations and statistical analysis. Here are some commonly used functions in numpy.random:

- `rand()`: generates an array of random samples from a uniform distribution over the interval [0, 1).
- `randn()`: generates an array of samples from a standard normal distribution (mean = 0, variance = 1).
- `randint()`: generates random integers from low (inclusive) to high (exclusive), where you can specify the size and shape of the output array.
- `random()`: generates an array of random floats between 0 and 1 (excluding 1).
- `choice()`: generates a random sample from a given 1D array, with replacement or without replacement.
- `shuffle()`: shuffles the elements in a given 1D array.
- `normal()`: generates an array of samples from a normal distribution with specified mean and standard deviation.


In [33]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
uni_array = np.random.random((3, 3))
print(uni_array)

# Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1
norm_array = np.random.normal(loc = 0, scale = 1, size = (3, 3))
print(norm_array)

# Create a 3x3 array of random integers in the interval [0, 10)
rand_int_array = np.random.randint(low = 0, high = 10, size = (3, 3))
print(rand_int_array)

[[0.34517572 0.73485715 0.97802204]
 [0.26860885 0.21435429 0.45992539]
 [0.13177993 0.17355146 0.50103694]]
[[-0.41906872  0.29326765 -1.12070206]
 [-1.31093232 -1.37388139  0.39575358]
 [-1.35720927 -1.65754914 -2.40962646]]
[[9 1 4]
 [6 2 2]
 [9 4 6]]


## The Basics of NumPy Arrays
Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas (Chapter 3) are built around the NumPy array. This section will present several examples using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.

We’ll cover a few categories of basic array manipulations here:
- **Attributes of arrays**: Determining the size, shape, memory consumption, and data types of arrays
- **Indexing of arrays**: Getting and setting the value of individual array elements
- **Slicing of arrays**: Getting and setting smaller subarrays within a larger array
- **Reshaping of arrays**: Changing the shape of a given array
- **Joining and splitting**: of arrays: Combining multiple arrays into one, and splitting one array into many

### Attributes of arrays
Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array)

In [34]:
# Creating different arrays
x1 = np.random.randint(10, size = 6) # One-dimensional array
x2 = np.random.randint(10, size = (3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size = (3, 4, 5)) # Three-dimensional array

# Printing array attributes
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

# Another useful attribute is the dtype
print("dtype:", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


## Array Indexing: Accessing Single Elements
If you are familiar with Python’s standard list indexing, indexing in NumPy will feel quite familiar. 
- In a one-dimensional array, you can access the ith value (counting from zero) by specifying the desired index in square brackets, just as with Python lists.
- To index from the end of the array, you can use negative indices.
- In a multidimensional array, you access items using a comma-separated tuple of indices.
- You can also modify values using any of the above index notation.
- Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don’t be caught unaware by this behavior

In [40]:
# You can access the ith value (counting from zero) by specifying the desired index
print(x1)
print(x1[[1, 4]])

# To index from the end of the array, you can use negative indices
print(x1[-2])

# In a multidimensional array, you access items using a comma-separated tuple of indices
print(x2)
print(x2[0, 0])

[6 3 3 2 9 8]
[3 9]
9
[[9 7 3 9]
 [4 6 9 3]
 [8 0 5 4]]
9


## Array Slicing: Accessing Subarrays
Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon `(:)` character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:
    
        x[start:stop:step]

If any of these are unspecified, they default to the values `start = 0`, `stop = size` of dimension, `step = 1`

In [56]:
# One-dimensional subarrays
# Create an array
x = np.arange(10)

print(x[:5]) # first five elements
print(x[5:]) # elements after index 5
print(x[4:7]) # middle subarray
print(x[::2]) # every other element
print(x[1::2]) # every other element, starting at index 1

# With negative step value
print(x[::-1]) # all elements, reversed
print(x[5::-2]) # reversed every other from index 5
print(x[6:1:-1]) # Inverted

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


array([6, 5, 4, 3, 2])

In [59]:
# Multidimensional subarrays
# Create an array
x2 = np.random.randint(10, size = (3, 4))
print(x2)

print(x2[:2, :3]) # two rows, three columns
print(x2[:3, ::2]) # all rows, every other column
print(x2[::-1, ::-1]) # subarray dimensions can even be reversed together

[[5 9 6 4]
 [1 4 9 1]
 [6 9 5 8]]
[[5 9 6]
 [1 4 9]]
[[5 6]
 [1 9]
 [6 5]]
[[8 5 9 6]
 [1 9 4 1]
 [4 6 9 5]]


In [62]:
# Accessing array rows and columns
print(x2[:, 0]) # first column of x2
print(x2[0, :]) # first row of x2

# In the case of row access, the empty slice can be omitted for a more compact syntax:
print(x2[0]) # equivalent to x2[0, :]

[5 1 6]
[5 9 6 4]
[5 9 6 4]


### Reshaping of Arrays
Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the `reshape()` method. Note that for this to work, the size of the initial array must match the size of the reshaped array.

In [69]:
# For example, if you want to put the numbers 1 through 9 in a 3×3 grid, you can do the following:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

# Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
x = np.array([1, 2, 3])
x.reshape((1, 3)) # row vector via reshape
x[np.newaxis, :] # row vector via newaxis

x.reshape((3, 1)) # column vector via reshape
x[:, np.newaxis] # column vector via newaxis

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting
All of the preceding routines worked on single arrays. It’s also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We’ll take a look at those operations here.

- **Concatenation of arrays**: Concatenation, or joining of two arrays in NumPy, is primarily accomplished through the routines `np.concatenate`, `np.vstack`, and `np.hstack`. 
- **Spliting of Arrays**: The opposite of concatenation is splitting, which is implemented by the functions `np.split`, `np.hsplit`, and `np.vsplit`.

In [70]:
# Concatenation of arrays
# np.concatenate takes a tuple or list of arrays as its first argument
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

# np.concatenate can also be used for two-dimensional arrays
grid = np.array([[1, 2, 3], 
                 [4, 5, 6]])

# concatenate along the first axis
np.concatenate([grid, grid])

# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis = 1)

array([1, 2, 3, 3, 2, 1])

In [72]:
# For working with arrays of mixed dimensions, it can be clearer to use the np.vstack
# (vertical stack) and np.hstack (horizontal stack) functions:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

# horizontally stack the arrays
y = np.array([[99],
              [99]])

np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [73]:
# For each of these, we can pass a list of indices giving the split points:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

# Notice that N split points lead to N + 1 subarrays. The related functions np.hsplit and np.vsplit are similar:
grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

left, right = np.hsplit(grid, [2])
print(left)
print(right)

[1 2 3] [99 99] [3 2 1]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
